name: e_comerce_app
description: "E-commerce app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^8.0.3
  get_it: ^7.6.8
  injectable: ^2.4.1
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  logger: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  rxdart: ^0.27.7
  path_provider: ^2.1.5
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  yandex_mapkit: ^4.1.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_bloc: ^9.1.0
  like_button: ^2.0.5
#  location: ^8.0.0
#  geolocator: ^13.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.9
  freezed: ^2.5.0
  auto_route_generator: ^8.0.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.4.0


flutter:
  uses-material-design: false
  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  output: lib/common/gen
  integrations:
    flutter_svg: true


